EDITIONS = {
    "en": {"lang": "eng", "parsoid": [0]},
    "es": {"lang": "spa", "parsoid": [0]},
    "fr": {"lang": "fra", "parsoid": [0], "kiwix": ("Conjugaison:",)},
    "ru": {"lang": "rus", "parsoid": [0]},
    "de": {"lang": "deu", "parsoid": [0], "kiwix": ("Flexion:",)},
    "zh": {"lang": "zho", "parsoid": [0]},
    "ja": {"lang": "jpn", "parsoid": [0]},
    "pl": {"lang": "pol", "parsoid": [0]},
    "el": {"lang": "ell", "parsoid": [0]},
    "nl": {
        "lang": "nld",
        "parsoid": [0],
        "main_ns_suffixes": ("/vervoeging", "/verbuiging"),
    },
    "th": {"lang": "tha", "parsoid": [0]},
    "fi": {"lang": "fin", "parsoid": [0], "kiwix": ("Liite:",)},
    "sv": {"lang": "swe", "parsoid": [0]},
    "simple": {"lang": "simple", "parsoid": [0]},
    "it": {"lang": "ita", "parsoid": [0], "kiwix": ("Appendice:Coniugazioni/",)},
    "pt": {"lang": "por", "parsoid": [0]},
    "vi": {"lang": "vie", "parsoid": [0]},
    "tr": {"lang": "tur", "parsoid": [0]},
    "ku": {"lang": "kur", "parsoid": [0], "kiwix": ("Tewandin:",)},
    "id": {"lang": "ind", "parsoid": [0]},
    "cs": {"lang": "ces", "parsoid": [0]},
    "ko": {"lang": "kor", "parsoid": [0]},
}
